# Generated by Django 2.2.1 on 2019-05-31 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_mu', models.FloatField()),
                ('rating_sigma', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=True)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_away_set', to='matchlog.Player')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_home_set', to='matchlog.Player')),
            ],
        ),
    ]
