# Generated by Django 2.2.1 on 2019-11-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchlog', '0002_match_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTeamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('points', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.MatchTeam')),
            ],
        ),
    ]
