# Generated by Django 2.2.1 on 2019-11-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchlog', '0003_matchteamset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSetPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.MatchPlayer')),
                ('match_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.MatchSet')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSetTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('match_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.MatchSet')),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchlog.MatchTeam')),
            ],
        ),
        migrations.DeleteModel(
            name='MatchTeamSet',
        ),
    ]
